### ISSUE TITLE
Conflict errors with pear1u on Centos 7 

### ISSUE THREAD

**Issue by sastek** [iuscommunity-pkg/pear1u#1]
Hi, when I try to install pear1u on a Centos 7 machine using "yum install pear1u" I am getting 2 conflict errors (see below)

I have PHP 7.1 installed (PHP71u), but it looks like pear1u wants to install PHP 7.0.25 dependencies. Can I just ignore these errors, or does pear1u not work with PHP 7.1?

Package pear1u is obsoleted by php-pear, trying to install 1:php-pear-1.10.5-2.el7.remi.noarch instead
Resolving Dependencies
--> Running transaction check
---> Package php-pear.noarch 1:1.10.5-2.el7.remi will be installed
--> Processing Dependency: php-posix for package: 1:php-pear-1.10.5-2.el7.remi.noarch
--> Running transaction check
---> Package php-process.x86_64 0:7.0.25-1.el7.remi will be installed
--> Processing Dependency: php-common(x86-64) = 7.0.25-1.el7.remi for package: php-process-7.0.25-1.el7.remi.x86_64
--> Running transaction check
---> Package php-common.x86_64 0:7.0.25-1.el7.remi will be installed
--> Processing Dependency: php-json(x86-64) = 7.0.25-1.el7.remi for package: php-common-7.0.25-1.el7.remi.x86_64
--> Running transaction check
---> Package php-json.x86_64 0:7.0.25-1.el7.remi will be installed
--> Processing Conflict: php71u-common-7.1.11-1.ius.centos7.x86_64 conflicts php-common < 7.1.11-1.ius.centos7
--> Processing Conflict: php71u-json-7.1.11-1.ius.centos7.x86_64 conflicts php-json < 7.1.11-1.ius.centos7
--> Finished Dependency Resolution
Error: php71u-common conflicts with php-common-7.0.25-1.el7.remi.x86_64
Error: php71u-json conflicts with php-json-7.0.25-1.el7.remi.x86_64
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

**Comment by b-harper** [comment]
Hey @sastek,

We do not do any testing or make any guarantees that IUS will work with other 3rd party repositories.  If you need both Remi and IUS repositories, you will need to add includes/excludes in the yum configuration files to avoid any conflicts.  I would not recommend not using a PHP stack from two different 3rd party repositories.

**Comment by sastek** [comment]
Hi, I didn't even notice that it was trying to pull from remi, what a silly mistake :)
