### ISSUE TITLE
pear1u conflicts with php71u

### ISSUE THREAD

**Issue by MadMind** [iuscommunity-pkg/pear1u#2]
I'm trying to install PHP 7.1 and PEAR on CentOS 7 using https://centos7.iuscommunity.org/ius-release.rpm and get the following error:
`Error: php72u-common conflicts with php71u-common-7.1.13-1.ius.centos7.x86_64`

Steps to reproduce:
 - Create new vagrant machine using `centos/7`
 - Run `rpm -i epel-release-latest-7.noarch.rpm`
 - Run `rpm -i ius-release-1.0-15.ius.centos7.noarch.rpm`
 - Run `yum install php71-cli`
 - Run `yum install pear1u`
Full output of last command
```
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirrors.cat.pdx.edu
 * epel: mirror.sjc02.svwh.net
 * extras: centos.mirrors.tds.net
 * ius: mirrors.kernel.org
 * updates: mirror.san.fastserv.com
Resolving Dependencies
--> Running transaction check
---> Package pear1u.noarch 1:1.10.5-1.ius.centos7 will be installed
--> Processing Dependency: php-posix for package: 1:pear1u-1.10.5-1.ius.centos7.noarch
--> Processing Dependency: php-xml for package: 1:pear1u-1.10.5-1.ius.centos7.noarch
--> Running transaction check
---> Package php71u-process.x86_64 0:7.1.14-1.ius.centos7 will be installed
---> Package php72u-xml.x86_64 0:7.2.2-1.ius.centos7 will be installed
--> Processing Dependency: php-common(x86-64) = 7.2.2-1.ius.centos7 for package: php72u-xml-7.2.2-1.ius.centos7.x86_64
--> Processing Dependency: libxslt.so.1(LIBXML2_1.0.11)(64bit) for package: php72u-xml-7.2.2-1.ius.centos7.x86_64
--> Processing Dependency: libxslt.so.1(LIBXML2_1.0.13)(64bit) for package: php72u-xml-7.2.2-1.ius.centos7.x86_64
--> Processing Dependency: libxslt.so.1(LIBXML2_1.0.18)(64bit) for package: php72u-xml-7.2.2-1.ius.centos7.x86_64
--> Processing Dependency: libxslt.so.1(LIBXML2_1.0.22)(64bit) for package: php72u-xml-7.2.2-1.ius.centos7.x86_64
--> Processing Dependency: libxslt.so.1(LIBXML2_1.0.24)(64bit) for package: php72u-xml-7.2.2-1.ius.centos7.x86_64
--> Processing Dependency: libexslt.so.0()(64bit) for package: php72u-xml-7.2.2-1.ius.centos7.x86_64
--> Processing Dependency: libxslt.so.1()(64bit) for package: php72u-xml-7.2.2-1.ius.centos7.x86_64
--> Running transaction check
---> Package libxslt.x86_64 0:1.1.28-5.el7 will be installed
---> Package php72u-common.x86_64 0:7.2.2-1.ius.centos7 will be installed
--> Processing Conflict: php72u-common-7.2.2-1.ius.centos7.x86_64 conflicts php-common < 7.2.2-1.ius.centos7
--> Processing Conflict: php72u-common-7.2.2-1.ius.centos7.x86_64 conflicts php71u-common
--> Finished Dependency Resolution
Error: php72u-common conflicts with php71u-common-7.1.14-1.ius.centos7.x86_64
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```

Do I need to use specific version of pear1u with PHP 7.1?

**Comment by MadMind** [comment]
Nevermind, I've found the solution. Need to install `php71u-xml` and `php71u-process` before `pear1u`.

**Comment by scottsb** [comment]
@MadMind Would you mind reopening this? I believe this is actually a bug that should be fixed. It shouldn't attempt to install a PHP 7.2 package as a dependency when you have PHP 7.1 installed.

**Comment by carlwgeorge** [comment]
@scottsb This should stay closed.  pear1u's dependencies can be satisfied by either php71u or php72u, so without enough of the dependencies already installed yum might try to pick a mix based on it's resolution logic.  This is the same behavior as one can observe with [installing phpMyAdmin](https://ius.io/FAQs/#im-trying-to-install-phpmyadmin-but-yum-is-failing-with-errors-from-ius-packages-why).  This is a tradeoff we accepted when we decided to use one pear package for all PHP stacks.  You can work around it in one of two ways:

1. Install php71u-cli, php71u-common, and php71u-xml before or at the same time as pear1u.

```
yum install pear1u php71u-{cli,common,xml}
```

2. Use the tech preview [yum4 (dnf)](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/7.6_release_notes/technology_previews_system_and_subscription_management#BZ1461652), which has better dependency resolution than stock yum.

```
# will resolve dependencies that match the currently installed PHP stack
yum4 install pear1u
```

**Comment by scottsb** [comment]
Makes sense. Thanks for the clarification. Glad to hear this kind of thing will be automatically taken care of with the new yum version.
